# Generated by Django 4.2.9 on 2024-01-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheonma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheonma_app.level'),
        ),
    ]
