# Generated by Django 4.2.9 on 2024-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheonma_app', '0002_alter_page_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
