# Generated by Django 4.2.9 on 2024-01-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheonma_app', '0004_remove_page_level_alter_level_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheonma_app.page'),
        ),
        migrations.AlterField(
            model_name='level',
            name='effect',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='lock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
