# Generated by Django 4.2.9 on 2024-01-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheonma_app', '0005_level_page_alter_level_effect_alter_level_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='cheonma_app.page'),
        ),
    ]
